### ISSUE TITLE
How to I run by Tags?

### ISSUE THREAD

**Issue by edricklacbayo** [serenity-bdd/serenity-cucumber4-starter#27]
How do I run by Tags?

![image](https://user-images.githubusercontent.com/28752767/76592165-7d662000-652d-11ea-8e18-e54364ae3abf.png)

![image](https://user-images.githubusercontent.com/28752767/76592172-85be5b00-652d-11ea-97e7-2d475ad00e7b.png)

![image](https://user-images.githubusercontent.com/28752767/76592185-8f47c300-652d-11ea-97d5-329c79aee9c6.png)

clean verify "-Dcucumber.options=--tags @lemniscate"

![image](https://user-images.githubusercontent.com/28752767/76594000-cec4de00-6532-11ea-9167-999903f22a4d.png)

It doesn't exeute the test, it just passes

**Comment by wakaleo** [comment]
You need quotes around the tags options - see https://johnfergusonsmart.com/running-serenity-bdd-tests-with-tags/
