### ISSUE TITLE
PendingException

### ISSUE THREAD

**Issue by edricklacbayo** [serenity-bdd/serenity-cucumber4-starter#28]
I tried to follow this guide and I get Pending Exception

![image](https://user-images.githubusercontent.com/28752767/77288493-ee1df100-6d12-11ea-87c4-c19a33d6338e.png)

Here is my CucumberTestSuite

![image](https://user-images.githubusercontent.com/28752767/77288510-f8d88600-6d12-11ea-9070-116eec6f9fef.png)

**Comment by shankar4a1** [comment]
I am also getting same exception after following guide step by step.Can some one help please

**Comment by wakaleo** [comment]
This starter project is deprecated now - try with the serenity-cucumber-starter project instead

**Comment by DayGitH** [comment]
Is it no longer possible to use Cucumber 4 with Serenity?

**Comment by wakaleo** [comment]
No. We have upgraded to Cucumber 5 which is not backward compatible.

**Comment by DayGitH** [comment]
Is there an ETA on release for that?

**Comment by wakaleo** [comment]
It was released in version 2.2.0

**Comment by DayGitH** [comment]
Ohhh. I just realised that serenity-cucumber-starter is using cucumber 5 and not cucumber 2. Thanks for your help!

**Comment by NerdishShah** [comment]
> This starter project is deprecated now - try with the serenity-cucumber-starter project instead

Until I failed to fix this issue myself by playing around with different versions and about to raise the issue here where noticed its already reported, there was no clue as such that this repository is deprecated. Please add deprecation message and archive the repository.
