### ISSUE TITLE
Serenity - JUnit 5

### ISSUE THREAD

**Issue by thiagopaschoal** [serenity-bdd/serenity-cucumber4-starter#40]
Hey guys!!

I have some projects who I use JUnit 5 as lib testing and I would like to know if Serenity-BDD has support for it? Are you already using JUnit 5? I had seen this PR, where you told that Serenity does not had support for JUnit 5 yet.

https://github.com/serenity-bdd/serenity-cucumber4-starter/issues/14

Could you help me with this question?

**Comment by wakaleo** [comment]
Serenity JUnit 5 support is in the works.

**Comment by thiagopaschoal** [comment]
Thanks @wakaleo !! Is there any specific project who I can use as example?
