### ISSUE TITLE
[Question] New features are not displayed in Requirements, Capabilities and Features sections

### ISSUE THREAD

**Issue by ismaelcabanas** [serenity-bdd/serenity-cucumber4-starter#5]
Hi Team,

I want to use Serenity Reporting with gradle in my company, and I am testing this tool. It is a great tool, but I have some problems.

I have cloned this Git repo and I have begun to play with it, and the first thing I have done is create a new feature, as the documentation recommend: I have created a new directory in **src/main/resouces/features** and I have created a new **feature** file. 

When I execute `gradle clean test -P=chrome` from my console it works fine but the report is not I expected. In the overall section appears the new feature
![Captura de pantalla 2019-06-25 a las 18 00 32](https://user-images.githubusercontent.com/4937330/60114185-9ea29880-9773-11e9-8d34-95857b46e989.png)

But, in the Requiremens, Capabilities and Features tabs, they are not displayed
![Captura de pantalla 2019-06-25 a las 18 06 13](https://user-images.githubusercontent.com/4937330/60114338-f5a86d80-9773-11e9-8c78-2ed22d0db038.png)
![Captura de pantalla 2019-06-25 a las 18 06 54](https://user-images.githubusercontent.com/4937330/60114390-0953d400-9774-11e9-8422-6de8954fe35b.png)

Furthermore, if I delete the Search feature and come back to execute `gradle clean test -P=chrome`, the **Search** feature appears...

What am I doing wrong?

Thanks in advance!

**Comment by wakaleo** [comment]
If you are running on Windows there is a known issue when you put a feature file in the root directory (src/test/resources/features). Generally you should place your feature files in sub-directories organised by capability/epic etc.

**Comment by ismaelcabanas** [comment]
I am using MacOS and the structure of my features is like this
<img width="296" alt="Captura de pantalla 2019-06-25 a las 23 11 46" src="https://user-images.githubusercontent.com/4937330/60134013-d96df600-979e-11e9-9fbc-7dbd6d36cedd.png">

But, when I execute the test gradle task, surprisingly, the report generated by Serenity is something like this
<img width="1050" alt="Captura de pantalla 2019-06-25 a las 23 15 59" src="https://user-images.githubusercontent.com/4937330/60134251-61540000-979f-11e9-8910-f724b62f3189.png">

I have displayed the report with several browsers, and the result is the same.

**Comment by wakaleo** [comment]
It looks like a Gradle-related issue of some kind. I reproduced it initially but running "gradle clean test aggregate" eventually worked. Not sure what it's due to.

**Comment by ismaelcabanas** [comment]
@wakaleo you are right. It must be a Gradle-related issue. I had this one in my build.gradle:
`acceptanceTest.finalizedBy(aggregate)`. And this task executed when I launched `gradle clean check`, but the reports were wrong.

I have commented this line and I have executed `gradle clean check aggregate` and now, the reports are generated correctly.

Thanks for your help!
