### ISSUE TITLE
Choose between Gradle and Maven

### ISSUE THREAD

**Issue by BartVanRaemdonck** [serenity-bdd/serenity-cucumber4-starter#9]
The starter project has a Gradle and a Maven setup, but I'm missing some instructions, if you want to use only Gradle or only Maven.
Just deleting the lib files doesn't do the trick.
So how do you config the project if you only want to use Gradle for example?
How do you safely remove the maven libs and pom file without breaking anything?

**Comment by wakaleo** [comment]
You don't need to delete anything - there is no obligation to use maven or the pom.xml file if you prefer to use the build.gradle script. If you really want to remove the Maven build script, just delete the pom.xml file.

**Comment by BartVanRaemdonck** [comment]
And what about all the maven libs?
Because if you delete the maven libs, then the project is broken.

**Comment by wakaleo** [comment]
That's not how maven works; if you delete the Maven dependencies Maven will just re-download them when needed. Same for Gradle. I don't know what "lib files" you are referring to though.

**Comment by BartVanRaemdonck** [comment]
![Picture 24](https://user-images.githubusercontent.com/11335721/63279796-f0fec200-c2a9-11e9-8b10-58b540a04c5f.jpg)

If I only want to use Gradle, I have to delete the pom.xml file, but also those maven lib files?
Otherwise the project is polluted?

**Comment by wakaleo** [comment]
That's the IntelliJ configuration; just reimport the project as a Gradle project.

**Comment by BartVanRaemdonck** [comment]
Ok, thank you!
